version: 2

models:
  - name: stg_invoices
    config:
      enabled : true
      tags: ['google_drive']

  - name: stg_invoices_2
    config:
      enabled : true
      tags: ['google_drive']
